using System;

namespace Entidades
{
    public class planillaDetalleTo
    {
        public string NRO_PLANILLA_COB { get; set; }
        public string COD_INSTITUCION { get; set; }
        public string COD_PTO_COB_CONSOLIDADO { get; set; }
        public string COD_CANAL_DSCTO { get; set; }
        public string FE_AÑO { get; set; }
        public string FE_MES { get; set; }
        public string NRO_CONTRATO { get; set; }
        public string COD_PER { get; set; }
        public decimal IMP_DOC { get; set; }
        public decimal IMP_COB { get; set; }
        public decimal IMP_COB_CTA_CTE { get; set; }
        public decimal IMP_DEV { get; set; }
        public string NRO_LETRA { get; set; }
        public string TOT_LETRA { get; set; }
        public string TIPO_PLANILLA { get; set; }
        public string COD_MOTIVO_NO_DESCONTADO { get; set; }
        public string OBSERVACION { get; set; }
        public string TIPO_GENERACION { get; set; }
        public string COD_PTO_COB { get; set; }
        public string COD_CREACION { get; set; }
        public DateTime FECHA_CREACION { get; set; }
        public string COD_DOC { get; set; }
        public string NRO_DOC { get; set; }
        public DateTime? FECHA_VEN { get; set; }
        public string COD_MOD { get; set; }
        public DateTime FECHA_MOD { get; set; }
        public string COD_SUCURSAL { get; set; }
        public bool OK { get; set; }
        //PARA REPORTE
        public DateTime FECHA_CONTRATO { get; set; }
        public string CLIENTE { get; set; }
        public string DESC_IDENTIDAD { get; set; }
        public string DNI { get; set; }
        public string DES_PROCESO { get; set; }
        public string NOM_MOTIVO_NO_DESCONTADO { get; set; }
        public string IMP_ENVIADO { get; set; }
        public string IMP_NO_DESCONTADO { get; set; }
        public string COD_PTO_VEN { get; set; }
        public DateTime FECHA_PLANILLA_COB { get; set; }
        public string DESC_PTO_VEN { get; set; }
        public string CUOTA { get; set; }
        public string DESC_PTO_COB { get; set; }
        public decimal MONTO_ENVIADO { get; set; }
        public string CATEG_MOTIVO { get; set; }
        public string CATEGORIA { get; set; }
        public decimal MONTO_RECIBIDO { get; set; }
        public decimal IMP_ENVIO { get; set; }
        public object A { get; set; }
        public object B { get; set; }
        public object C { get; set; }
        public object D { get; set; }
        public object E { get; set; }
        public object F { get; set; }
        public object G { get; set; }
        public object H { get; set; }
        public object I { get; set; }
        public object J { get; set; }
        public object K { get; set; }
        public object L { get; set; }
        public object M { get; set; }
        public object N { get; set; }
        public object Ñ { get; set; }
        public object O { get; set; }
        public object P { get; set; }
        public object Q { get; set; }
        public object R { get; set; }
        public object S { get; set; }
        public object T { get; set; }
        public object U { get; set; }
        public object V { get; set; }
        public object W { get; set; }
        public object X { get; set; }
        public object Y { get; set; }
        public object Z { get; set; }
        public decimal I01 { get; set; }
        public decimal I02 { get; set; }
        public decimal I03 { get; set; }
        public decimal I04 { get; set; }
        public decimal I05 { get; set; }
        public decimal I06 { get; set; }
        public decimal I07 { get; set; }
        public decimal I08 { get; set; }
        public decimal I09 { get; set; }
        public decimal I10 { get; set; }
        public decimal I11 { get; set; }
        public decimal I12 { get; set; }
        public decimal I13 { get; set; }
        public decimal I14 { get; set; }
        public decimal I15 { get; set; }
        public decimal I16 { get; set; }
        public decimal I17 { get; set; }
        public decimal I18 { get; set; }
        public decimal I19 { get; set; }
        public decimal I20 { get; set; }
        public decimal I21 { get; set; }
        public decimal I22 { get; set; }
        public int Q01 { get; set; }
        public int Q02 { get; set; }
        public int Q03 { get; set; }
        public int Q04 { get; set; }
        public int Q05 { get; set; }
        public int Q06 { get; set; }
        public int Q07 { get; set; }
        public int Q08 { get; set; }
        public int Q09 { get; set; }
        public int Q10 { get; set; }
        public int Q11 { get; set; }
        public int Q12 { get; set; }
        public int Q13 { get; set; }
        public int Q14 { get; set; }
        public int Q15 { get; set; }
        public int Q16 { get; set; }
        public int Q17 { get; set; }
        public int Q18 { get; set; }
        public string COD_UBICACION { get; set; }

    }
}
