using System;

namespace Entidades
{
    public class precontratoCabeceraTo
    {
        public string COD_SUCURSAL { get; set; }
        public string NRO_PRESUPUESTO { get; set; }
        public string COD_PER { get; set; }
        public string COD_CLASE { get; set; }
        public string FE_AÑO { get; set; }
        public string FE_MES { get; set; }
        public DateTime FECHA_PRE { get; set; }
        public string COD_MONEDA { get; set; }
        public decimal TIPO_CAMBIO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string STATUS_PV { get; set; }
        public int NRO_DIAS { get; set; }
        public string COD_PER_ELAB { get; set; }
        public string COD_PER_APROB { get; set; }
        public string STATUS_APROB { get; set; }
        public string STATUS_ANUL { get; set; }
        public string STATUS_CIERRE { get; set; }
        public string COD_VENDEDOR { get; set; }
        public string CONDICION_VENTA { get; set; }
        public string COD_CONTACTO { get; set; }
        public DateTime? FECHA_APROB { get; set; }
        public string TIPO_PRECIO { get; set; }
        public string OBSERVACION { get; set; }
        public string NRO_REPORTE { get; set; }
        public DateTime FEC_REPORTE { get; set; }
        public string COD_PROGRAMA { get; set; }
        public string PERIODO { get; set; }
        public string NRO_SEMANA { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string TIPO_PLANILLA { get; set; }
        public string COD_ALMACEN { get; set; }
        public string COD_NIVEL1 { get; set; }
        public string COD_NIVEL2 { get; set; }
        public string COD_NIVEL3 { get; set; }
        public decimal SUELDO_BASICO { get; set; }
        public decimal SUELDO_BRUTO { get; set; }
        public decimal OTROS_DSCTOS { get; set; }
        public decimal JUDICIALES { get; set; }
        public decimal NETO_COBRAR { get; set; }
        public decimal TOTAL_CONTRATO { get; set; }
        public int NRO_CUOTAS { get; set; }
        public decimal IMP_CUOTA_INICIAL { get; set; }
        public decimal IMP_CUOTA_MES { get; set; }
        public DateTime? FEC_PRIMER_VENC { get; set; }
        public string NOMBRE_PC { get; set; }
        public string TIPO_USU { get; set; }
        public string COD_USU { get; set; }
        public int NRO_DIAS_VENC { get; set; }
        public DateTime FEC_CUO_MEN { get; set; }
        public string COD_SUB_PTO_VEN { get; set; }
        public string COD_CANAL_DSCTO { get; set; }
        public string COD_PTO_COB { get; set; }
        public string COD_TIPO_VENTA { get; set; }
        public string COD_MODALIDAD_VTA { get; set; }
        public string COD_LUG_VTA { get; set; }
        public string COD_INSTITUCION { get; set; }
        public decimal IMPORTE_PROTECCION { get; set; }
        public string COD_KIT { get; set; }
        public decimal DSCTO_TOTAL { get; set; }
        public string NRO_REPORTE1 { get; set; }
        public string DESC_PER { get; set; }
        public string DESC_ALMACEN { get; set; }
        public string VENDEDOR { get; set; }
        public string DESC_PTO_COB { get; set; }
        public string DESC_PTO_VEN { get; set; }
        public string DIR_DOMI { get; set; }
        public string NRO_FONO { get; set; }
        public string DIR_TRABAJO { get; set; }
        public string TLF_CEL { get; set; }
        public string COND_CLIE { get; set; }
        public string Desc_Dep { get; set; }
        public string DESC_KIT { get; set; }
        public string CANAL_DSCTO { get; set; }
        public DateTime FECHA_CREA { get; set; }
        public string DIST_DOMI { get; set; }
        public string DEP_DOMI { get; set; }
        public string DIST_TRABAJO { get; set; }
        public string DEP_TRABAJO { get; set; }
        public string COD_USU_CREA { get; set; }
        public string DESC_PROGRAMA { get; set; }
        public string DIGITADOR { get; set; }
        public string NOM_SEMANA { get; set; }
        public string COD_MOV { get; set; }
        public string STATUS_PRE_APROB { get; set; }
        public string NRO_BENEFICIARIOS { get; set; }
        public string APROB_POR { get; set; }
        public string DNI { get; set; }
        public DateTime FECHA_REPORTE_DESDE { get; set; }
        public DateTime FECHA_REPORTE_HASTA { get; set; }
        public string DES_IDENTIDAD { get; set; }
        public string DES_PROCESO { get; set; }
        public DateTime FECHA_GRAL { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public DateTime FECHA_CONTRATO_DESDE { get; set; }
        public DateTime FECHA_CONTRATO_HASTA { get; set; }
        public bool STATUS_REPORTE { get; set; }
        public bool STATUS_CONTRATO { get; set; }
        public string STATUS_NRO_REPORTE { get; set; }
        public bool CERRAR_NRO_REPORTE { get; set; }
        public string COD_NIVEL_INSTITUCION { get; set; }
        public decimal SALDOxCOBRA { get; set; }
        public DateTime? FE_ULT_CAMBIO { get; set; }
        public int NRO_DE_CAMBIOS { get; set; }
        public bool OP_APROB { get; set; }
        public bool OP_CONTR { get; set; }
        public bool OP_REPO { get; set; }
        public string INSTITUCION_PTO_COB { get; set; }
        public string INSTITUCION_PTO_COB_UBICACION { get; set; }
        public string DESC_INSTITUCION { get; set; }
        public string INSTITUCION_PTO_COB2 { get; set; }
    }

}
